---
abstract: ~
author:
  - 'Ingy döt Net <ingy@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: JS::YAML
name: JS-YAML
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
version: 0.11
